### ISSUE TITLE
styles&page

### ISSUE THREAD

**Issue by Okekejr** [Okekejr/cineclix#1]
# Task:

- [x] cleanup default next.js files
- [x] add chakra theme and styles
- [x] download and import fonts
- [x] add 404-page redirect
