### ISSUE TITLE
navbar&pageLayout

### ISSUE THREAD

**Issue by Okekejr** [Okekejr/cineclix#4]
# Tasks:

- [x] create navbar component
- [x] import and create the app logo
- [x] build page layout
