### ISSUE TITLE
allSections&types

### ISSUE THREAD

**Issue by Okekejr** [Okekejr/cineclix#6]
# Tasks:

- [x] create the homepage
- [x] create all sections { topRated, upcoming, popularMovies, nowPlaying }
- [x] create and import types
- [x] create mini-movies and big-movie cards for some sections
- [x] make everything responsive up until now
