### ISSUE TITLE
moviesPage,SEO,favicon

### ISSUE THREAD

**Issue by Okekejr** [Okekejr/cineclix#8]
# Tasks:

- [x] create the movies page
- [x] pass the ids and create the movie UI
- [x] add next seo
- [x] edit the favicon
